# Generated by Django 4.0.5 on 2022-06-21 04:21

import accounts.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=9821152307, max_length=10, validators=[accounts.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('813e1dd2-4d12-4b63-a81d-c30306d43018'), max_length=255, null=True),
        ),
    ]
