# Generated by Django 4.0.5 on 2022-06-21 04:23

import accounts.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_alter_profile_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('1ed2f3ca-1ec6-4588-9c47-2734f46eeb2f'), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='9821152307', max_length=10, validators=[accounts.validators.validate_phone]),
        ),
    ]
