# Generated by Django 4.0.5 on 2022-06-26 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_verify_token_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('92b9a5a4-0853-4ccf-829d-b9fc12cea1f0'), max_length=255, null=True),
        ),
    ]
