# Generated by Django 4.0.5 on 2022-06-26 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('1113d66f-b82c-4ec9-8ffd-1d9d3b7f38db'), max_length=255, null=True),
        ),
    ]
