# Generated by Django 4.0.5 on 2022-06-26 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('d858153f-2d7f-4bc9-82d1-fead44db8668'), max_length=255, null=True),
        ),
    ]
