# Generated by Django 4.0.5 on 2022-06-26 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('e6f5496d-57a5-4cc0-b2fa-af0d5e6c96ea'), max_length=255, null=True),
        ),
    ]
