# Generated by Django 4.0.5 on 2022-06-26 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('c3ca0272-334d-4dd4-9b60-626a63260f09'), max_length=255, null=True),
        ),
    ]
