# Generated by Django 4.0.5 on 2022-06-27 02:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(default=uuid.UUID('412df8cd-40a7-4be0-9e87-25bb8e3ba988'), max_length=255, null=True),
        ),
    ]
