# Generated by Django 4.0.5 on 2022-06-26 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAuth', '0002_alter_client_client_id_alter_client_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='df3427686104365e2a70507a0b0e3a0f', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_secret',
            field=models.CharField(default='9630654d77d0ead0a9fc6bf9a7d96ac06c7e6e41fc0cb6a5fd934f53f3848a14', max_length=1000),
        ),
        migrations.CreateModel(
            name='ClientScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAuth.client')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CAuth.scope')),
            ],
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
