# Generated by Django 4.0.5 on 2022-06-27 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CAuth', '0004_remove_client_scope_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default='86a7897eda2bdc5186435eddeb0bb254', max_length=1000),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_secret',
            field=models.CharField(default='4fda03c47f7e349472a5fc0663ea619b4156e8064c77a2b46d93bcd313537e48', max_length=1000),
        ),
    ]
